@ShopEtum.MinimalApi_HostAddress = https://localhost:7221
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImtldmluIiwic3ViIjoia2V2aW4iLCJqdGkiOiJkNmRkZTFlMyIsImF1ZCI6InNob3BldHVtYXBpIiwibmJmIjoxNzM3MTE1ODk5LCJleHAiOjE3NDQ4OTE4OTksImlhdCI6MTczNzExNTkwMCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.dE18BBDuKwotNYSPDRT6yLjckMcoXqaNynnH2Zr6V5g

### CreateProduct
POST {{ShopEtum.MinimalApi_HostAddress}}/products
Content-Type: application/json
Accept: application/json
Authentication: Bearer {{Token}}

{
  "name": "Sample Product",
  "price": 19.99,
  "description": "A sample product description"
}

### GetProduct
GET {{ShopEtum.MinimalApi_HostAddress}}/products/1
Accept: application/json
Authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImtldmluIiwic3ViIjoia2V2aW4iLCJqdGkiOiJkNmRkZTFlMyIsImF1ZCI6InNob3BldHVtYXBpIiwibmJmIjoxNzM3MTE1ODk5LCJleHAiOjE3NDQ4OTE4OTksImlhdCI6MTczNzExNTkwMCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.dE18BBDuKwotNYSPDRT6yLjckMcoXqaNynnH2Zr6V5g

### ListProducts
GET {{ShopEtum.MinimalApi_HostAddress}}/products
Accept: application/json

### CreateCart
POST {{ShopEtum.MinimalApi_HostAddress}}/carts
Content-Type: application/json
Accept: application/json
 
### CreateCartWithOrders
POST {{ShopEtum.MinimalApi_HostAddress}}/carts/with-orders
Content-Type: application/json
Accept: application/json

{
  "orders": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 2,
      "quantity": 1
    }
  ]
}

### GetCart
GET {{ShopEtum.MinimalApi_HostAddress}}/carts/8
Accept: application/json
 