@ShopEtum.MinimalApi_HostAddress = http://localhost:5209
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImtldmluIiwic3ViIjoia2V2aW4iLCJqdGkiOiJiOTQ1ZWJiNyIsImF1ZCI6InNob3BldHVtYXBpIiwibmJmIjoxNzM3MTEwNDg1LCJleHAiOjE3NDQ4ODY0ODUsImlhdCI6MTczNzExMDQ4NiwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.pIXlwgJdwW4yeUCd92AWFBT9R5YXR3x8j3W1gDzIi60

### CreateProduct
POST {{ShopEtum.MinimalApi_HostAddress}}/products
Content-Type: application/json
Accept: application/json
Authentication: Bearer {{Token}}

{
  "name": "Sample Product",
  "price": 19.99,
  "description": "A sample product description"
}

### GetProduct
GET {{ShopEtum.MinimalApi_HostAddress}}/products/1
Accept: application/json
Authentication: Bearer {{Token}}

### ListProducts
GET {{ShopEtum.MinimalApi_HostAddress}}/products
Accept: application/json

### CreateCart
POST {{ShopEtum.MinimalApi_HostAddress}}/carts
Content-Type: application/json
Accept: application/json
 
### CreateCartWithOrders
POST {{ShopEtum.MinimalApi_HostAddress}}/carts/with-orders
Content-Type: application/json
Accept: application/json

{
  "orders": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 2,
      "quantity": 1
    }
  ]
}

### GetCart
GET {{ShopEtum.MinimalApi_HostAddress}}/carts/8
Accept: application/json
 