@ShopEtum.MinimalApi_HostAddress = https://localhost:7221

### CreateProduct
POST {{ShopEtum.MinimalApi_HostAddress}}/products
Content-Type: application/json
Accept: application/json

### GetProduct
GET {{ShopEtum.MinimalApi_HostAddress}}/products/1
Accept: application/json
Authorization: Bearer {{Token}}

### ListProducts
GET {{ShopEtum.MinimalApi_HostAddress}}/products
Accept: application/json
